# -*- coding: utf-8 -*-
"""COS30082 ROC and AUC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ba9jPeTumLWW2ioav59X89BFNjZQ5YIw
"""

!pip install torch torchvision scikit-learn matplotlib

import os
import torch
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
from PIL import Image
from torchvision import transforms

CKPT_DIR = '/content/drive/MyDrive/COS30082Project/checkpoints'
VERIF_DIR = '/content/drive/MyDrive/COS30082Project/realDATA/verification_data'
PAIRS_FILE = '/content/drive/MyDrive/COS30082Project/realDATA/verification_pairs_val.txt'

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)

embed_net = torch.load(
    os.path.join(CKPT_DIR, 'embed_net_full.pt'),
    map_location=device,
    weights_only=False  # ensure full model object is loaded
)
embed_net.eval()

val_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize([0.5]*3, [0.5]*3)
])

pairs = []
with open(PAIRS_FILE, 'r') as f:
    for line in f:
        img1, img2, lbl = line.strip().split()
        pairs.append((img1, img2, int(lbl)))
print(f"Loaded {len(pairs)} verification trials")

# Compute similarity scores and labels
scores = []
labels = []

for img1, img2, lbl in pairs:
    # Load images as PIL
    # Ensure we use the basename to avoid nested 'verification_data/'
    path1 = os.path.join(VERIF_DIR, os.path.basename(img1))
    path2 = os.path.join(VERIF_DIR, os.path.basename(img2))
    im1 = Image.open(path1).convert('RGB')
    im2 = Image.open(path2).convert('RGB')
    # Apply transform and move to device
    t1 = val_transform(im1).unsqueeze(0).to(device)
    t2 = val_transform(im2).unsqueeze(0).to(device)
    # Compute embeddings
    with torch.no_grad():
        e1 = embed_net(t1).cpu().numpy().flatten()
        e2 = embed_net(t2).cpu().numpy().flatten()
    # Cosine similarity as score
    sim = np.dot(e1, e2) / (np.linalg.norm(e1) * np.linalg.norm(e2))
    scores.append(sim)
    labels.append(lbl)

# AUC calculation
fpr, tpr, thresholds = roc_curve(labels, scores)
roc_auc = auc(fpr, tpr)
print(f"Verification AUC: {roc_auc:.4f}")

# Plot ROC curve
plt.figure(figsize=(6,6))
plt.plot(fpr, tpr, label=f'AUC = {roc_auc:.3f}', linewidth=2)
plt.plot([0,1], [0,1], 'k--', label='Random')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve for Face Verification')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()