# -*- coding: utf-8 -*-
"""COS30082 Project Facial Recognition and Emotion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zZLZ4MkJuhMzSPQUMqiwh6Ox-wAAinz9
"""

!pip install torch torchvision scikit-learn matplotlib

!cp -r /content/drive/MyDrive/COS30082Project/realDATA/classification_data /content/classification_data

import os, time, random
import torch
from torch import nn, optim
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms, datasets
import matplotlib.pyplot as plt
import torchvision
from tqdm.auto import tqdm

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)

data_dir = '/content/drive/MyDrive/COS30082Project/realDATA/classification_data'
ckpt_dir = '/content/drive/MyDrive/COS30082Project/checkpoints'

"""Transforms for classification"""

batch_size = 64
train_transform = transforms.Compose([
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(15),
    transforms.ToTensor(),
    transforms.Normalize([0.5]*3, [0.5]*3)
])

val_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize([0.5]*3, [0.5]*3)
])

"""DataLoaders"""

all_classes = [d for d in os.listdir(os.path.join(data_dir,'train_data')) if os.path.isdir(os.path.join(data_dir,'train_data',d))]
num_subset = min(1200, len(all_classes))
selected_classes = all_classes[:num_subset]
print(f"Training classification on {num_subset}/{len(all_classes)} classes")

def make_filtered_dataset(root, transform, classes):
    ds = datasets.ImageFolder(root, transform)
    new_samples = []
    for path,label in ds.samples:
        cls_name = ds.classes[label]
        if cls_name in classes:
            new_label = classes.index(cls_name)
            new_samples.append((path, new_label))
    ds.samples = new_samples
    ds.classes = classes
    ds.class_to_idx = {c:i for i,c in enumerate(classes)}
    return ds

train_ds = make_filtered_dataset(os.path.join(data_dir,'train_data'), train_transform, selected_classes)
val_ds   = make_filtered_dataset(os.path.join(data_dir,'val_data'),   val_transform,   selected_classes)
test_ds  = make_filtered_dataset(os.path.join(data_dir,'test_data'),  val_transform,   selected_classes)

train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True,  num_workers=4, pin_memory=True)
val_loader   = DataLoader(val_ds,   batch_size=batch_size, shuffle=False, num_workers=4, pin_memory=True)
test_loader  = DataLoader(test_ds,  batch_size=batch_size, shuffle=False, num_workers=4, pin_memory=True)

"""##CNN model

"""

class SimpleCNN(nn.Module):
    def __init__(self, num_classes):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(3,32,3,padding=1),  nn.BatchNorm2d(32),  nn.ReLU(), nn.MaxPool2d(2),  #64->32
            nn.Conv2d(32,64,3,padding=1), nn.BatchNorm2d(64),  nn.ReLU(), nn.MaxPool2d(2),  #32->16
            nn.Conv2d(64,128,3,padding=1),nn.BatchNorm2d(128), nn.ReLU(), nn.MaxPool2d(2),  #16->8
            nn.Conv2d(128,256,3,padding=1),nn.BatchNorm2d(256), nn.ReLU(), nn.MaxPool2d(2)  #8->4
        )
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Dropout(0.5),
            nn.Linear(256*4*4,512), nn.ReLU(), nn.Dropout(0.5),
            nn.Linear(512,num_classes)
        )
    def forward(self,x):
        x = self.features(x)
        return self.classifier(x)

"""Instantiate"""

num_classes = len(selected_classes)
cls_model = SimpleCNN(num_classes).to(device)
print('Model architecture:', cls_model)

"""Train classification model (Supervised Classfication)"""

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(cls_model.parameters(), lr=1e-3, weight_decay=1e-4)  # weight_decay = L2 regularization
scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=10, gamma=0.1)
epochs = 50
loss_hist, acc_hist = [], []

for ep in range(1,epochs+1):
    start = time.time()
    cls_model.train()
    total_loss = 0
    for imgs, labels in tqdm(train_loader, desc=f"[Cls] Ep {ep}/{epochs}", leave=False):
        imgs, labels = imgs.to(device), labels.to(device)
        optimizer.zero_grad()
        out = cls_model(imgs)
        loss = criterion(out, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    avg_loss = total_loss / len(train_loader)
    scheduler.step()

    # Validation
    cls_model.eval(); correct=total=0
    with torch.no_grad():
        for imgs, labels in val_loader:
            imgs, labels = imgs.to(device), labels.to(device)
            pred = cls_model(imgs).argmax(dim=1)
            correct += (pred==labels).sum().item(); total += labels.size(0)
    val_acc = 100*correct/total
    loss_hist.append(avg_loss); acc_hist.append(val_acc)
    print(f"[Cls] Ep {ep}/{epochs} Loss {avg_loss:.4f} ValAcc {val_acc:.2f}% Time {time.time()-start:.1f}s")

"""Test accuracy evaluation"""

cls_model.eval(); test_correct=test_total=0
with torch.no_grad():
    for imgs, labels in test_loader:
        imgs, labels = imgs.to(device), labels.to(device)
        pred = cls_model(imgs).argmax(dim=1)
        test_correct += (pred==labels).sum().item(); test_total += labels.size(0)
print(f"[Cls] Test Acc: {100*test_correct/test_total:.2f}%")

"""checkpoint"""

# Save trained classification model so it can be reloaded after disconnects
cls_state_path = os.path.join(ckpt_dir, 'cls_model_final_checkpoint_1.pth')
torch.save(cls_model.state_dict(), cls_state_path)
print(f"Saved classification model state dict to: {cls_state_path}")
#full model
cls_full_path = os.path.join(ckpt_dir, 'cls_model_full_checkpoint_1.pt')
torch.save(cls_model, cls_full_path)
print(f"Saved full classification model to: {cls_full_path}")

"""Embeddings extractor"""

cls_embed = nn.Sequential(*list(cls_model.children())[:-1], nn.Flatten()).to(device)

"""Training Metric Learning (Triplet Loss)"""

class TripletDataset(Dataset):
    def __init__(self, root, transform):
        self.transform = transform
        # 1) collect only classes with ≥2 valid images
        self.classes = []
        self.paths   = {}
        for c in sorted(os.listdir(root)):
            cls_dir = os.path.join(root, c)
            if not os.path.isdir(cls_dir):
                continue
            imgs = [f for f in os.listdir(cls_dir)
                    if os.path.isfile(os.path.join(cls_dir, f))
                    and f.lower().endswith(('.jpg','.jpeg','.png'))]
            if len(imgs) < 2:
                continue
            self.classes.append(c)
            self.paths[c] = [os.path.join(cls_dir, f) for f in imgs]

        # 2) flatten anchor list
        self.samples = [(p, c) for c, ps in self.paths.items() for p in ps]

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        anc_path, anc_cls = self.samples[idx]
        # positive
        pos_path = random.choice([p for p in self.paths[anc_cls] if p != anc_path])
        # negative from a different class
        neg_cls  = random.choice([c for c in self.classes if c != anc_cls])
        neg_path = random.choice(self.paths[neg_cls])

        def load(p):
            img = torchvision.io.read_image(p).float() / 255.0
            img = transforms.ToPILImage()(img)
            return self.transform(img)

        return load(anc_path), load(pos_path), load(neg_path)

trip_ds = TripletDataset(os.path.join(data_dir,'train_data'), train_transform)
trip_loader = DataLoader(trip_ds, batch_size=32, shuffle=True, num_workers=4, pin_memory=True)

a, p, n = trip_ds[0]
print('Anchor shape:', a.shape, 'Positive shape:', p.shape, 'Negative shape:', n.shape)

import matplotlib.pyplot as plt
fig, axes = plt.subplots(1,3, figsize=(9,3))
for img, ax, title in zip([a,p,n], axes, ['Anchor','Positive','Negative']):
    img_np = img.permute(1,2,0).numpy()
    ax.imshow((img_np * 0.5 + 0.5))
    ax.set_title(title)
    ax.axis('off')
plt.show()

"""Embedding network (same SimpleCNN backbone)"""

embed_net = nn.Sequential(
    cls_model.features,
    nn.Flatten(),
    # 256*4*4 = 4096 features
    nn.Linear(256*4*4, 256),
    nn.ReLU(),
    nn.Linear(256, 128),
).to(device)

triplet_loss = nn.TripletMarginLoss(margin=1.0)
opt2 = optim.Adam(embed_net.parameters(), lr=1e-4)

"""actual training metric learning"""

for ep in range(1,epochs+1):
    start=time.time(); embed_net.train(); tot=0
    for a,p,n in trip_loader:
        a,p,n=[x.to(device) for x in (a,p,n)]
        opt2.zero_grad()
        ea,epos,en = embed_net(a), embed_net(p), embed_net(n)
        loss=triplet_loss(ea,epos,en)
        loss.backward(); opt2.step()
        tot+=loss.item()
    print(f"[Trip] Ep {ep}/{epochs} Loss {tot/len(trip_loader):.4f} Time {time.time()-start:.1f}s")

"""checkpoint"""

# Save triplet embedding model after training
tri_state = os.path.join(ckpt_dir, 'tri_embed_net_final_checkpoint_1.pth')
torch.save(embed_net.state_dict(), tri_state)
print(f"Saved triplet embedding state dict to: {tri_state}")
tri_full = os.path.join(ckpt_dir, 'tri_embed_net_full_checkpoint_1.pt')
torch.save(embed_net, tri_full)
print(f"Saved full triplet embedding model to: {tri_full}")

plt.figure(figsize=(10,4))
plt.subplot(1,2,1); plt.plot(range(1,epochs+1), loss_hist, 'o-'); plt.title('Cls Train Loss')
plt.subplot(1,2,2); plt.plot(range(1,epochs+1), acc_hist, 'o-', color='orange'); plt.title('Cls Val Acc')
plt.tight_layout(); plt.show()

"""# Identification Top-1 Accuracy"""

from sklearn.neighbors import KNeighborsClassifier
import numpy as np

def extract_embeddings(model, loader, embed_dim=None):
    model.eval()
    feats, labels = [], []
    with torch.no_grad():
        for imgs, lbls in loader:
            imgs = imgs.to(device)
            out = model(imgs).cpu().numpy()
            feats.append(out)
            labels.extend(lbls.numpy())
    feats = np.vstack(feats)
    labels = np.array(labels)
    return feats, labels

"""Create DataLoaders without augmentation for embedding extraction"""

de_emb_transform = val_transform
train_ds_eval = datasets.ImageFolder(os.path.join(data_dir,'train_data'), de_emb_transform)
val_ds_eval   = datasets.ImageFolder(os.path.join(data_dir,'val_data'),   de_emb_transform)
train_loader_eval = DataLoader(train_ds_eval, batch_size=64, shuffle=False, num_workers=4)
val_loader_eval   = DataLoader(val_ds_eval,   batch_size=64, shuffle=False, num_workers=4)

train_embs_cls, train_lbls = extract_embeddings(cls_embed, train_loader_eval)
val_embs_cls,   val_lbls   = extract_embeddings(cls_embed, val_loader_eval)
train_embs_tri, _          = extract_embeddings(embed_net, train_loader_eval)
val_embs_tri,   _          = extract_embeddings(embed_net, val_loader_eval)

"""1-NN for classification embeddings"""

knn_cls = KNeighborsClassifier(n_neighbors=1, metric='euclidean')
knn_cls.fit(train_embs_cls, train_lbls)
acc_cls_knn = knn_cls.score(val_embs_cls, val_lbls)

"""1-NN for triplet embeddings"""

knn_tri = KNeighborsClassifier(n_neighbors=1, metric='euclidean')
knn_tri.fit(train_embs_tri, train_lbls)
acc_tri_knn = knn_tri.score(val_embs_tri, val_lbls)

"""#Results"""

print(f"Top-1 Identification Accuracy:\n"
      f"  Classification Embeddings: {acc_cls_knn*100:.2f}%")
print(f"Triplet Embeddings:         {acc_tri_knn*100:.2f}%")

"""#Saving"""

torch.save(cls_model.state_dict(), os.path.join(ckpt_dir, 'cnnV1.1_state_dict.pth'))
torch.save(cls_model,           os.path.join(ckpt_dir, 'cnnV1.1.pt'))

"""Embedding network state dict and full model"""

torch.save(embed_net.state_dict(), os.path.join(ckpt_dir, 'embed_cnnV1.1_state_dict.pth'))
torch.save(embed_net,              os.path.join(ckpt_dir, 'embed_cnnV1.1.pt'))